"""add role enum to users

Revision ID: e1b6795d7ae0
Revises: 0641d8c0ef15
Create Date: 2025-08-12 15:15:47.995744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b6795d7ae0'
down_revision: Union[str, Sequence[str], None] = '0641d8c0ef15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the enum type
role_enum = sa.Enum('admin', 'user', name='roleenum')


def upgrade() -> None:
    # 1️⃣ Create the ENUM type in Postgres
    role_enum.create(op.get_bind(), checkfirst=True)

    # 2️⃣ Add the column using that ENUM type
    op.add_column(
        'users',
        sa.Column('role', role_enum, nullable=False, server_default='user')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')

    # 2️⃣ Drop the ENUM type
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
